#!/usr/bin/env bash
# Write <app>/src/wifi_creds.erl from the git-ignored stt/main/wifi_secrets.h (never committed).
#   atomvm/gen_wifi_creds.sh atomvm/apps/m0_probe
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
H="$HERE/../stt/main/wifi_secrets.h"
ssid=$(sed -n 's/.*WIFI_SSID *"\(.*\)".*/\1/p' "$H")
pass=$(sed -n 's/.*WIFI_PASS *"\(.*\)".*/\1/p' "$H")
cat > "$1/src/wifi_creds.erl" <<ERL
%% Generated by atomvm/gen_wifi_creds.sh -- git-ignored, do not commit.
-module(wifi_creds).
-export([get/0]).
get() -> {"$ssid", "$pass"}.
ERL
