"""Emit stt/main/citrinet_tables.h: the exact Hann window and slaney mel filterbank
from the checkpoint's preprocessor (not recomputed -- bit-for-bit the same floats the
Python pipeline uses), plus the CTC vocabulary.

  uv run gen_c_tables.py
"""
from pathlib import Path

import torch

from citrinet import load_model

OUT = Path(__file__).resolve().parent.parent / "stt" / "main" / "citrinet_tables.h"


def f32(v: float) -> str:
    return repr(float(torch.tensor(v, dtype=torch.float32))) + "f"


def main():
    _, feat, vocab, _ = load_model()
    win = feat.window.float()
    fb = feat.fb.float()  # [80, 257]
    L = ["// Generated by export/gen_c_tables.py -- do not edit.",
         "#pragma once", "#include <stdint.h>", "",
         f"#define MEL_N_FFT {feat.n_fft}", f"#define MEL_WIN {feat.win_length}",
         f"#define MEL_HOP {feat.hop}", f"#define MEL_BINS {fb.shape[1]}",
         f"#define MEL_N {fb.shape[0]}", f"#define VOCAB_N {len(vocab)}  // blank = VOCAB_N", "",
         f"static const float MEL_WINDOW[{len(win)}] = {{"]
    L += ["    " + ", ".join(f32(x) for x in win[i:i + 6].tolist()) + "," for i in range(0, len(win), 6)]
    L += ["};", "", "// Sparse filterbank: row m covers bins [start, start+len).",
          "typedef struct { uint16_t start, len, off; } mel_row_t;"]
    rows, weights = [], []
    for m in range(fb.shape[0]):
        nz = torch.nonzero(fb[m]).flatten()
        s, e = int(nz[0]), int(nz[-1]) + 1
        rows.append((s, e - s, len(weights)))
        weights += fb[m, s:e].tolist()
    L.append(f"static const mel_row_t MEL_ROWS[{len(rows)}] = {{")
    L += [f"    {{{s}, {n}, {o}}}," for s, n, o in rows]
    L += ["};", f"static const float MEL_WEIGHTS[{len(weights)}] = {{"]
    L += ["    " + ", ".join(f32(x) for x in weights[i:i + 6]) + "," for i in range(0, len(weights), 6)]
    L += ["};", "", f"static const char *const VOCAB[{len(vocab)}] = {{"]
    L += ["    " + ", ".join('"' + t.replace("\\", "\\\\").replace('"', '\\"') + '"' for t in vocab[i:i + 8]) + ","
          for i in range(0, len(vocab), 8)]
    L += ["};", ""]
    OUT.write_text("\n".join(L))
    print(f"-> {OUT}: window {len(win)}, filterbank {len(weights)} nonzero weights, vocab {len(vocab)}")


if __name__ == "__main__":
    main()
